### ISSUE TITLE
Add a way to extend js and scss or less in parent theme

### ISSUE THREAD

**Issue by SebastiaanKloos** [kloos-dev/oc-themeupdate-plugin#2]

**Comment by alvaro-canepa** [comment]
JS can be extended using Laravel.mix and Lodash.assign, having a base jQuery object.
Or even better, using a base class with TS

**Comment by SebastiaanKloos** [comment]
I was thinking about adding JS and CSS files to the theme by using`System\Classes\CombineAssets`
